# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.datetime_start = QtWidgets.QDateTimeEdit(MainWindow)
        self.datetime_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.datetime_start.setObjectName("datetime_start")
        self.horizontalLayout_3.addWidget(self.datetime_start)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.datetime_end = QtWidgets.QDateTimeEdit(MainWindow)
        self.datetime_end.setObjectName("datetime_end")
        self.horizontalLayout_3.addWidget(self.datetime_end)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table = QtWidgets.QTableWidget(MainWindow)
        self.table.setMinimumSize(QtCore.QSize(460, 0))
        self.table.setAutoScroll(True)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setAlternatingRowColors(True)
        self.table.setRowCount(0)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.horizontalLayout_2.addWidget(self.table)
        self.group_summary = QtWidgets.QGroupBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_summary.sizePolicy().hasHeightForWidth())
        self.group_summary.setSizePolicy(sizePolicy)
        self.group_summary.setMaximumSize(QtCore.QSize(300, 16777215))
        self.group_summary.setObjectName("group_summary")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_summary)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_summary = QtWidgets.QPlainTextEdit(self.group_summary)
        self.text_summary.setObjectName("text_summary")
        self.gridLayout_2.addWidget(self.text_summary, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.group_summary)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_count = QtWidgets.QLabel(MainWindow)
        self.label_count.setObjectName("label_count")
        self.horizontalLayout.addWidget(self.label_count)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame_details = QtWidgets.QFrame(MainWindow)
        self.frame_details.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_details.setLineWidth(1)
        self.frame_details.setMidLineWidth(0)
        self.frame_details.setObjectName("frame_details")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_details)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.text_details = QtWidgets.QPlainTextEdit(self.frame_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_details.sizePolicy().hasHeightForWidth())
        self.text_details.setSizePolicy(sizePolicy)
        self.text_details.setMaximumSize(QtCore.QSize(16777215, 100))
        self.text_details.setObjectName("text_details")
        self.gridLayout.addWidget(self.text_details, 0, 0, 1, 1)
        self.button_hide = QtWidgets.QPushButton(self.frame_details)
        self.button_hide.setObjectName("button_hide")
        self.gridLayout.addWidget(self.button_hide, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_details)

        self.retranslateUi(MainWindow)
        self.button_hide.clicked.connect(self.frame_details.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Loglyzer GUI"))
        self.datetime_start.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd hh:mm:ss"))
        self.label.setText(_translate("MainWindow", "To"))
        self.datetime_end.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd hh:mm:ss"))
        self.group_summary.setTitle(_translate("MainWindow", "Summary"))
        self.label_count.setText(_translate("MainWindow", "Total: %d"))
        self.button_hide.setText(_translate("MainWindow", "Hide"))

